# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  image: latest

# Build all formats
formats: all

python:
  version: "3.8"
  # Install our python package before building the docs
  install:
    - requirements: docs/requirements/docs-requirements.txt
  system_packages: false


# Build documentation in the docs/source/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
